### ISSUE TITLE
http2 fd too many files

### ISSUE THREAD

**Issue by bit4bit** [docker/libchan#43]
hi,

i'm implementing a server with libchan and http2, they work well, but they fail after some minutes with the error *fd too many files open*,when debug see the descriptor for libchan.Message.Fd create by the http2.StreamReceiver.Receive method used on the server, they grow and grow..
look, simple test,
**ulimit -n 80**
then running de server the Fd grow:
  * adialer-handler2014/07/09 00:01:14 msg.Fd &{%!s(*os.file=&{9  <nil> 0})}
  * adialer-handler2014/07/09 00:01:15 msg.Fd &{%!s(*os.file=&{13  <nil> 0})}
  * adialer-handler2014/07/09 00:01:15 msg.Fd &{%!s(*os.file=&{15  <nil> 0})}
  * adialer-handler2014/07/09 00:01:17 msg.Fd &{%!s(*os.file=&{23  <nil> 0})}
  * adialer-handler2014/07/09 00:01:29 msg.Fd &{%!s(*os.file=&{29  <nil> 0})}
  * ...
  * adialer-handler2014/07/09 00:01:34 msg.Fd &{%!s(*os.file=&{72  <nil> 0})}
 
and boom!, i'm find a solution and it's closing the descriptor (msg.Fd.Close()) when then server finish the response,

there a better way?

thanks

**Comment by dmcgowan** [comment]
This issue should be fixed with the updated libchan interface
